sudo: enabled
dist: xenial

services: mongodb

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose2

before_script: cd Server
script:
  - python -m nose2 --with-coverage

after_success:
  - coverage report
  - coveralls
